### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by StringKe** [iredcap/pay#14]
- [ ] 境外支付 (商业版?)
- [x] 现有功能,异常错误捕捉 (如mkdir创建的时候提示已有文件夹的时候)
- [ ] 提现操作
- [ ] 由子域名修改成目录后遗留的小问题地址修改( 支持可选域名/目录模式两种? )
- [ ] 前台注册审核
- [ ] 支持前台封闭模式 ( 私有化系统不开放使用? )
- [ ] 完善商户功能( 代理,子代理,提成? )
- [ ] 前台页面完善( 文档,渠道等 )
- [ ] 安装方面  ( 检测了redis 但是不需要设置相关链接信息? )
- [ ] 后台筛选时间方面( 不知道是我操作有误?我怎么选时间都无法正确的筛选出数据 )
- [ ] API的IP验证 ( 应支持域名和统配 )

**Comment by Brianwaring** [comment]
境外支付 Impossible
mkdir是在没有目录的时候才会执行 这个不担心
提现操作我会后续完善
子域名问题不是我的锅  我自己都懒得改
前台注册审核靠邮件注册验证  无需审核（可以考虑，但绝对没必要）
私有化自行解决   非技术性问题
代理功能很烦 我实话说我开始就没打算写代理  现在要重构很心烦
页面等自己改
安装redis数据配置我觉得技术人员应该会自行解决  （可以考虑，但是我觉得没必要，大部分小白都是默认端口和ip）
筛选时间绝对是姿势不对 老子就能查得到
API的IP和域名验证 尽量  统配我不搞（统配自己做正则验证）
有其他继续提交，谢谢：）
