### ISSUE TITLE
[develop] 渠道账号列表的 cnl_id 为空

### ISSUE THREAD

**Issue by 1948919174** [iredcap/pay#23]
添加渠道账号后 发现没有数据查看数据表 cm_pay_account 发现新添加的数据的 cnl_id 为 0

**Comment by 1948919174** [comment]
初次打开的时候无法加载数据出来

**Comment by 1948919174** [comment]
![image](https://user-images.githubusercontent.com/41410211/50369745-51cbe280-05d5-11e9-8c22-719a3d39c03e.png)
没有附加 cnl_id

**Comment by Brianwaring** [comment]
等待
